### ISSUE TITLE
Add usage example

### ISSUE THREAD

**Issue by malaire** [icidasset/elm-material-icons#3]
Add an example of how to use `Icon` within Html.

**Comment by icidasset** [comment]
Hey, thanks for making an issue!

There's an example in the README.
But I assume you saw that, so I guess it's not clear that `Filled.offline_bolt` can be used in `Html`? 🤔 
I'll add some type signatures to the example soon.

**Comment by icidasset** [comment]
Made code comment in readme slightly better.

**Comment by dbrgn** [comment]
For the record (since I was a bit confused as well):

`Icon msg` is an alias for `Svg msg`.

To convert a `Svg msg` to a `Html msg`, use the `svg` function: https://package.elm-lang.org/packages/elm/svg/latest/Svg#svg

**Comment by dbrgn** [comment]
Oops, that's actually wrong, you can us an `Icon msg` directly just like a `Html msg`!

(The reason why this initially didn't work for me was that I'm using `Html.Styled.Html` by default, so I had to pass the icon through `fromUnstyled` first.)

**Comment by icidasset** [comment]
Yeah, it's an alias for: Int -> [Coloring](https://package.elm-lang.org/packages/icidasset/elm-material-icons/latest/Material-Icons-Types#Coloring) -> Svg msg

I didn't want to make an alias, but I had to because of Elm's limitation on the size of `docs.json` file 🙈 
And yeah exactly, you can just use it together with `Html msg`

**Comment by dbrgn** [comment]
Anyways, thanks @icidasset for the lib, once I figured out how, it was quite convenient to use!
